### PR TITLE
Move demo to `website` branch

### PR DESCRIPTION
**Pull request by wooorm**
* Also move UMD bundle to root to remove empty folder

Closes GH-477.

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
How will `website` branch differ from `gh-pages` branch? Or will they be the same?

**Comment by wooorm** [comment]
Website is clean: no checked in built files. gh-pages is dirty: because GH requires served files to be checked in

**Comment by wooorm** [comment]
(this is already live btw, so the difference can be seen: https://github.com/remarkjs/react-markdown/tree/gh-pages vs https://github.com/remarkjs/react-markdown/tree/website)

**Comment by ChristianMurphy** [comment]
So there will be three branches?
`main` for the library source code, `website` for the website source code, and `gh-pages` for the website deployment?

**Comment by wooorm** [comment]
Yeah, that’s my plan! You have to have gh-pages, because the generated files are there. Moving the demo files to a different branch separates the two things: one a library, another a (small) site, which have very different goals

**Review by ChristianMurphy — APPROVED** [review]
fine by me.
I've usually put the site source in a folder on the `main` branch, but I'd be open to trying a dedicated branch for the site source.

**Pull request merged**
