### PR TITLE
Remove compiled library

### PR DESCRIPTION
**Pull request by wooorm**
I don’t think we need a prebuilt `lib/`; the source code is usable as-is

### CODE REVIEW

**Review by ChristianMurphy — APPROVED** [review]
The main difference appears to be that we'd lose TS as a transpile to guarantee that output is ES2015.
Though scanning through the files it appears they are already ES2015.

**Comment by wooorm** [comment]
How is TS being used to transpile?

**Comment by ChristianMurphy** [comment]
Perhaps I misread the tsconfig, but my impression was that it read the source dir and copied/transpiled to the lib?

**Comment by wooorm** [comment]
I don’t think so, `build:lib` was doing it:

```
"build:lib": "rimraf lib/ && babel src/ --quiet --copy-files -d lib/",
```

I think TS was checking *both* (might be a mistake I made recently), but as they were basically copies, that didn’t do much

**Pull request merged**
