### PR TITLE
Refactor architecture diagram to use mermaid flowchart syntax

### PR DESCRIPTION
**Pull request by cychitivav**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

Refactored the architecture diagram using Mermaid flowchart syntax to improve readability and enhance the visual representation for a clearer understanding of the project structure, improving professionalism despite losing the URLs of links between blocks.

### CODE REVIEW

**Review by remcohaszing — CHANGES_REQUESTED** [review]
I like it. Except that the AST types are now no longer links.

**Comment by cychitivav** [comment]
> I like it. Except that the AST types are now no longer links.


Yes, I noticed that, but I couldn't find any information on how to add URLs to the links within the Mermaid diagrams. As an alternative, I thought of preserving the URLs by adding them as a footer or citation in Markdown.

```mermaid
flowchart LR
  markdown[markdown] --> remark[remark]
  subgraph remarkMarkdown[react-markdown]
    direction LR
    remark -- mdast --> remarkPlugins[remark plugins]
    remarkPlugins -- mdast --> remarkRehype[remark-rehype]
    remarkRehype -- hast --> rehypePlugins[rehype plugins]
    rehypePlugins -- hast --> components[components]
  end
  components --> react[react elements]

  click markdown "https://commonmark.org" "Markdown Specification"
  click remark "https://github.com/remarkjs/remark" "Remark Documentation"
  click remarkPlugins "https://github.com/remarkjs/remark/blob/main/doc/plugins.md" "Remark Plugins"
  click remarkRehype "https://github.com/remarkjs/remark-rehype" "Remark Rehype Documentation"
  click rehypePlugins "https://github.com/rehypejs/rehype/blob/main/doc/plugins.md" "Rehype Plugins Documentation"
  click components "#appendix-b-components" "Components Documentation"
```
> - *mdast*: https://github.com/syntax-tree/mdast
> - *hast*: https://github.com/syntax-tree/hast

**Comment by wooorm** [comment]
I really have my doubts on this. I do not want to live in a world where ASCII-diagrams are unprofessional. I don’t think all those zoom controls are useful. I think this is fine.

@ChristianMurphy I think you originally made this graph? Thoughts?

**Comment by remcohaszing** [comment]
I like this, but I do have my doubts considering the readme may be displayed in places that don’t support mermaid.

**Comment by wooorm** [comment]
@ChristianMurphy Ping :)

**Comment by ChristianMurphy** [comment]
> I think you originally made this graph?

I made this, and based it off the style of the unified architecture diagram https://github.com/unifiedjs/unified?tab=readme-ov-file#overview

I quite like Mermaid as a diagramming tool and don't have any objections to moving this over.
It would be kinda nice if the links on the lines could remain, but that's something that may need to be raised upstream at mermaid.

**Comment by wooorm** [comment]
OK. I will not block mermaid per-se. I personally like ASCII more.

I do think that splitting this graph up into both a graph, and then some links under it, is not an improvement.

If there is a way to fix that, I am 🤷‍♂️ to this PR.
If there currently no way to link mdast and hast, then I am :-1: on this PR. I think @remcohaszing too?

@cychitivav Can you somehow link mdast/hast? Report upstream?

**Comment by remcohaszing** [comment]
I’m also leaning no, but mostly because the Mermaid diagram might not be rendered in places other than GitHub.

**Comment by wooorm** [comment]
OK, I’ll close this then. I appreciate you contributing, @cychitivav. Thanks, but no thanks!

**Pull request closed without merging**
