### PR TITLE
update tests for tables

### PR DESCRIPTION
**Pull request by ChristianMurphy**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

discovered in https://github.com/micromark/micromark/pull/106
the unit tests no longer align with how tables are styled

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
Good news, the tests pass now

```
 test.jsx
• • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • • •   (96 / 96)

  Total:     96
  Passed:    96
  Skipped:   0
  Duration:  419.48ms
```

bad news, the test coverage has dropped?

```
ERROR: Coverage for lines (99.72%) does not meet global threshold (100%)
ERROR: Coverage for branches (99.45%) does not meet global threshold (100%)
ERROR: Coverage for statements (99.72%) does not meet global threshold (100%)
```

I find this strange since it doesn't add logic, or remove tests, the coverage should be the same as before?

**Review by wooorm — COMMENTED** [review]
Wait, who is adding `text-align:none`? 🤔

**Comment by ChristianMurphy** [comment]
Just based off timing I suspect https://github.com/micromark/micromark-extension-gfm-table/releases/tag/1.0.5

**Comment by wooorm** [comment]
Could be, but feels slightly unexpected to me? could it be react related? 🤔

**Comment by ChristianMurphy** [comment]
React was last updated in March, and tests have passed several times in that time span :thinking: 
https://github.com/facebook/react/releases/tag/v17.0.2

**Comment by ChristianMurphy** [comment]
cross linking a related issue https://github.com/remarkjs/remark-gfm/issues/29

**Comment by wooorm** [comment]
weird, will look into it soon

**Comment by wooorm** [comment]
The original tests is how it should be

**Pull request closed without merging**
