### PR TITLE
Added better documentation for renderer props

### PR DESCRIPTION
**Pull request by el1f**
Do you think there's a better way to display this kind of information?
References #247

### CODE REVIEW

**Comment by rexxars** [comment]
Adding props is a nice touch, but I don't really like how this looks in a table. The description takes up most of the width and the props are hard to read jammed at the end. It also doesn't scale very well on smaller (mobile) devices.

Don't have a clear picture of what a better solution would be right now. Will give it some thought.

**Comment by el1f** [comment]
You have a point. Gonna try with another configuration. Maybe having a list with `code` props on a new line could help

**Comment by el1f** [comment]
Tried doing it with a separate renderer props section, with links this could prove as a less hard to approach implementation

**Comment by SalahAdDin** [comment]
Good!

**Pull request closed without merging**
