### PR TITLE
Fix two bugs in `website` branch

### PR DESCRIPTION
**Pull request by fritx**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

Fix two bugs in `website` branch:

1. [fix error source.gfm not registered](https://github.com/remarkjs/react-markdown/commit/e46d5d4039f77bc45f6efc445afaf7223f4d3934) -- Local development for newcomers
2. [fix editor lost completely once empty](https://github.com/remarkjs/react-markdown/commit/cbb4a60e102a3e67881e4a8b0ac866ff8e80b49f) -- UI bug, also improved the availble area for selecting

### CODE REVIEW

**Comment by wooorm** [comment]
hi, thanks!

Can you actually solve the error though? Replace `source.gfm` / `sourceGfm` with `text.md`

**Comment by wooorm** [comment]
Thanks, used your other commit!

**Comment by fritx** [comment]
> Thanks, used your other commit!

Sure, but without swtiching to padding from margin, a scrollbar will appear even when the editor is empty because there are an extra margin along with 100% height...

```diff
-margin: 8px;
+padding: 8px;
```

**Comment by wooorm** [comment]
OK, if that's important, can you make another PR?

**Pull request closed without merging**
