### PR TITLE
Fix TypeScript bug by adding workaround

### PR DESCRIPTION
**Pull request by Methuselah96**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

Follow-up to https://github.com/remarkjs/react-markdown/pull/675. Adds `| undefined` as suggested in https://github.com/microsoft/TypeScript/issues/48242#issuecomment-1067348119.

Fixes this build error:
```
ERROR in ../../.yarn/__virtual__/react-markdown-virtual-1089d10e66/0/cache/react-markdown-npm-8.0.0-3d725f3756-61412ecd18.zip/node_modules/react-markdown/lib/react-markdown.d.ts 47:32-56
TS2307: Cannot find module 'mdast-util-to-hast/lib' or its corresponding type declarations.
    45 |   remarkPlugins?: import('unified').PluggableList | undefined
    46 |   rehypePlugins?: import('unified').PluggableList | undefined
  > 47 |   remarkRehypeOptions?: import('mdast-util-to-hast/lib').Options | undefined
       |                                ^^^^^^^^^^^^^^^^^^^^^^^^
    48 | }
    49 | export type LayoutOptions = {
    50 |   className?: string | undefined
```

### CODE REVIEW

**Comment by Methuselah96** [comment]
Not sure why bb is having trouble.

**Comment by wooorm** [comment]
This goes against the idea of using TS through JSDoc, to solve an issue where TypeScript does not support PnP.
I’d rather use JSDoc as intended, where possible, and have TypeScript solve its issues, instead of applying unexplainable patches?

Related-to: https://github.com/syntax-tree/mdast-util-gfm/pull/1#issuecomment-1067756832.

**Comment by wooorm** [comment]
Any thoughts on my comment? I’m leaning on seeing this as an issue TS should solve.

**Comment by wooorm** [comment]
Where would that have to be added? Because the error line includes that undefined already

**Comment by wooorm** [comment]
Oh I’m up for an explicit `undefined`, sure :+1:, but I’d say report back that it’s really weird that you have to this one weird trick to get completely unrelated behavior 🤷‍♂️

**Comment by Methuselah96** [comment]
PR updated. I agree, feel free to add a comment to https://github.com/microsoft/TypeScript/issues/48242. I haven't gotten a response to my last two comments.

**Comment by wooorm** [comment]
Thanks, released! https://github.com/remarkjs/react-markdown/releases/tag/8.0.2

**Pull request merged**
