### PR TITLE
Make minified source available to all tools

### PR DESCRIPTION
**Pull request by david-bezero**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests (not applicable)

### Description of changes

Support other tools which cannot work with ES Modules (e.g. Jest). The necessary code is already available but using a proprietary key in package.json (for unpkg). This adds standards-compliant config to make it available to other tooling which needs it.

### CODE REVIEW

**Comment by david-bezero** [comment]
the test failure seems to be because some build tooling is incompatible with the latest change to (experimental) loaders in Node 18.6 (unrelated to this change)

**Comment by ChristianMurphy** [comment]
There is a dual package hazard when exporting both CJS and ESM.
It has been discussed at some length at https://github.com/remarkjs/remark/issues/969#issuecomment-1068875448 and https://github.com/unifiedjs/unified/issues/121#issuecomment-804711549
It can cause real problems, trying to work around Jest-specific limitations.

There are some suggestions on how to make Jest play nicely with ESM in https://github.com/remarkjs/react-markdown/issues/635

**Comment by david-bezero** [comment]
@ChristianMurphy I guess note that the dual package hazard only applies to packages which contain meaningful global state (which, as far as I can see, this one doesn't). Also you're already _providing_ the dual packages; this PR just makes them both _available_ to the tooling, so I hope you might reconsider this decision.

For now, the only workaround available to users is this rather nasty config:

```js
  moduleNameMapper: {
    'react-markdown': '<rootDir>/node_modules/react-markdown/react-markdown.min.js',
  },
```

**Comment by ChristianMurphy** [comment]
The dual package hazard has several pitfalls and risks, global state is just one of them.
In addition, some remark/rehype plugins do use global state.

Having to configure around a bug/limitation of Jest is an acceptable trade-off, vs the risks and known issues of dual packaging.
And I'm hopeful in the future Jest will make ESM fully supported and seamless https://github.com/facebook/jest/issues/9430

**Pull request closed without merging**
